version: '3'
services:
  php:
    build: ./php
    ports:
      - 8080:80
    volumes:
      - ./www/html:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ow200416002

  pgadmin4:
    image: dpage/pgadmin4:4.2
    ports:
      - 8888:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: password
    hostname: pgadmin4
    depends_on:
      - db
volumes:
    .data: {}